updates

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -333,28 +333,40 @@ jobs:
       # - destroy-environment   
       # - revert-migrations 
 
-#   smoke-test:
-#     docker:
-#       # Lightweight Docker image 
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Get backend url
-#           command: |
-#             # your code here
-#       - run:
-#           name: Backend smoke test.
-#           command: |
-#             # your code here
-#       - run:
-#           name: Frontend smoke test.
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+
+  smoke-test:
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      # - checkout
+      - run:
+          name: Backend smoke test.
+          command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            
+            BACKEND_URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
+            
+            if curl -s $BACKEND_URL | grep "ok"
+            then
+              echo "Backend works"
+              exit 0
+            else
+              exit 1
+            fi
+
+      - run:
+          name: Frontend smoke test.
+          command: |
+            FRONTEND_URL=http://udapeople-0c973f4.s3-website-us-east-1.amazonaws.com
+            
+            if curl -s $FRONTEND_URL | grep "welcome"
+            then
+              echo "Frontend works"
+              exit 1
+            else
+              exit 2
+            fi
+      # Here's where you will add some code to rollback on failure  
 
 #   cloudfront-update:
 #     docker:
@@ -429,11 +441,11 @@ workflows:
           # requires: [deploy-infrastructure]
       # - run-migrations
           # requires: [configure-infrastructure]
-      - deploy-frontend
+      # - deploy-frontend
       #     requires: [run-migrations]
       # - deploy-backend
       #     requires: [run-migrations]
-      # - smoke-test:
+      - smoke-test
       #     requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
       #     requires: [smoke-test]
